/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WelcomeImport } from './routes/welcome'
import { Route as LoginImport } from './routes/login'
import { Route as ChatImport } from './routes/chat'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthCallbackImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardLayoutRouteImport } from './routes/_authenticated/_dashboardLayout/route'
import { Route as AuthenticatedDashboardLayoutWorkspaceSettingsImport } from './routes/_authenticated/_dashboardLayout/workspace-settings'
import { Route as AuthenticatedDashboardLayoutNotificationsImport } from './routes/_authenticated/_dashboardLayout/notifications'
import { Route as AuthenticatedDashboardLayoutKnowledgeImport } from './routes/_authenticated/_dashboardLayout/knowledge'
import { Route as AuthenticatedDashboardLayoutInboxImport } from './routes/_authenticated/_dashboardLayout/inbox'
import { Route as AuthenticatedOrchestratorOrchestratorIdRouteImport } from './routes/_authenticated/orchestrator/$orchestratorId/route'
import { Route as AuthenticatedOrchestratorOrchestratorIdPlaygroundImport } from './routes/_authenticated/orchestrator/$orchestratorId/playground'
import { Route as AuthenticatedOrchestratorOrchestratorIdDeploymentImport } from './routes/_authenticated/orchestrator/$orchestratorId/deployment'
import { Route as AuthenticatedOrchestratorOrchestratorIdConfigurationImport } from './routes/_authenticated/orchestrator/$orchestratorId/configuration'

// Create/Update Routes

const WelcomeRoute = WelcomeImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ChatRoute = ChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardLayoutRouteRoute =
  AuthenticatedDashboardLayoutRouteImport.update({
    id: '/_dashboardLayout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedDashboardLayoutWorkspaceSettingsRoute =
  AuthenticatedDashboardLayoutWorkspaceSettingsImport.update({
    id: '/workspace-settings',
    path: '/workspace-settings',
    getParentRoute: () => AuthenticatedDashboardLayoutRouteRoute,
  } as any)

const AuthenticatedDashboardLayoutNotificationsRoute =
  AuthenticatedDashboardLayoutNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardLayoutRouteRoute,
  } as any)

const AuthenticatedDashboardLayoutKnowledgeRoute =
  AuthenticatedDashboardLayoutKnowledgeImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedDashboardLayoutRouteRoute,
  } as any)

const AuthenticatedDashboardLayoutInboxRoute =
  AuthenticatedDashboardLayoutInboxImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedDashboardLayoutRouteRoute,
  } as any)

const AuthenticatedOrchestratorOrchestratorIdRouteRoute =
  AuthenticatedOrchestratorOrchestratorIdRouteImport.update({
    id: '/orchestrator/$orchestratorId',
    path: '/orchestrator/$orchestratorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedOrchestratorOrchestratorIdPlaygroundRoute =
  AuthenticatedOrchestratorOrchestratorIdPlaygroundImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => AuthenticatedOrchestratorOrchestratorIdRouteRoute,
  } as any)

const AuthenticatedOrchestratorOrchestratorIdDeploymentRoute =
  AuthenticatedOrchestratorOrchestratorIdDeploymentImport.update({
    id: '/deployment',
    path: '/deployment',
    getParentRoute: () => AuthenticatedOrchestratorOrchestratorIdRouteRoute,
  } as any)

const AuthenticatedOrchestratorOrchestratorIdConfigurationRoute =
  AuthenticatedOrchestratorOrchestratorIdConfigurationImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AuthenticatedOrchestratorOrchestratorIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_dashboardLayout': {
      id: '/_authenticated/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardLayoutRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/orchestrator/$orchestratorId': {
      id: '/_authenticated/orchestrator/$orchestratorId'
      path: '/orchestrator/$orchestratorId'
      fullPath: '/orchestrator/$orchestratorId'
      preLoaderRoute: typeof AuthenticatedOrchestratorOrchestratorIdRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/_dashboardLayout/inbox': {
      id: '/_authenticated/_dashboardLayout/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutInboxImport
      parentRoute: typeof AuthenticatedDashboardLayoutRouteImport
    }
    '/_authenticated/_dashboardLayout/knowledge': {
      id: '/_authenticated/_dashboardLayout/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutKnowledgeImport
      parentRoute: typeof AuthenticatedDashboardLayoutRouteImport
    }
    '/_authenticated/_dashboardLayout/notifications': {
      id: '/_authenticated/_dashboardLayout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutNotificationsImport
      parentRoute: typeof AuthenticatedDashboardLayoutRouteImport
    }
    '/_authenticated/_dashboardLayout/workspace-settings': {
      id: '/_authenticated/_dashboardLayout/workspace-settings'
      path: '/workspace-settings'
      fullPath: '/workspace-settings'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutWorkspaceSettingsImport
      parentRoute: typeof AuthenticatedDashboardLayoutRouteImport
    }
    '/_authenticated/orchestrator/$orchestratorId/configuration': {
      id: '/_authenticated/orchestrator/$orchestratorId/configuration'
      path: '/configuration'
      fullPath: '/orchestrator/$orchestratorId/configuration'
      preLoaderRoute: typeof AuthenticatedOrchestratorOrchestratorIdConfigurationImport
      parentRoute: typeof AuthenticatedOrchestratorOrchestratorIdRouteImport
    }
    '/_authenticated/orchestrator/$orchestratorId/deployment': {
      id: '/_authenticated/orchestrator/$orchestratorId/deployment'
      path: '/deployment'
      fullPath: '/orchestrator/$orchestratorId/deployment'
      preLoaderRoute: typeof AuthenticatedOrchestratorOrchestratorIdDeploymentImport
      parentRoute: typeof AuthenticatedOrchestratorOrchestratorIdRouteImport
    }
    '/_authenticated/orchestrator/$orchestratorId/playground': {
      id: '/_authenticated/orchestrator/$orchestratorId/playground'
      path: '/playground'
      fullPath: '/orchestrator/$orchestratorId/playground'
      preLoaderRoute: typeof AuthenticatedOrchestratorOrchestratorIdPlaygroundImport
      parentRoute: typeof AuthenticatedOrchestratorOrchestratorIdRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedDashboardLayoutRouteRouteChildren {
  AuthenticatedDashboardLayoutInboxRoute: typeof AuthenticatedDashboardLayoutInboxRoute
  AuthenticatedDashboardLayoutKnowledgeRoute: typeof AuthenticatedDashboardLayoutKnowledgeRoute
  AuthenticatedDashboardLayoutNotificationsRoute: typeof AuthenticatedDashboardLayoutNotificationsRoute
  AuthenticatedDashboardLayoutWorkspaceSettingsRoute: typeof AuthenticatedDashboardLayoutWorkspaceSettingsRoute
}

const AuthenticatedDashboardLayoutRouteRouteChildren: AuthenticatedDashboardLayoutRouteRouteChildren =
  {
    AuthenticatedDashboardLayoutInboxRoute:
      AuthenticatedDashboardLayoutInboxRoute,
    AuthenticatedDashboardLayoutKnowledgeRoute:
      AuthenticatedDashboardLayoutKnowledgeRoute,
    AuthenticatedDashboardLayoutNotificationsRoute:
      AuthenticatedDashboardLayoutNotificationsRoute,
    AuthenticatedDashboardLayoutWorkspaceSettingsRoute:
      AuthenticatedDashboardLayoutWorkspaceSettingsRoute,
  }

const AuthenticatedDashboardLayoutRouteRouteWithChildren =
  AuthenticatedDashboardLayoutRouteRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteRouteChildren,
  )

interface AuthenticatedOrchestratorOrchestratorIdRouteRouteChildren {
  AuthenticatedOrchestratorOrchestratorIdConfigurationRoute: typeof AuthenticatedOrchestratorOrchestratorIdConfigurationRoute
  AuthenticatedOrchestratorOrchestratorIdDeploymentRoute: typeof AuthenticatedOrchestratorOrchestratorIdDeploymentRoute
  AuthenticatedOrchestratorOrchestratorIdPlaygroundRoute: typeof AuthenticatedOrchestratorOrchestratorIdPlaygroundRoute
}

const AuthenticatedOrchestratorOrchestratorIdRouteRouteChildren: AuthenticatedOrchestratorOrchestratorIdRouteRouteChildren =
  {
    AuthenticatedOrchestratorOrchestratorIdConfigurationRoute:
      AuthenticatedOrchestratorOrchestratorIdConfigurationRoute,
    AuthenticatedOrchestratorOrchestratorIdDeploymentRoute:
      AuthenticatedOrchestratorOrchestratorIdDeploymentRoute,
    AuthenticatedOrchestratorOrchestratorIdPlaygroundRoute:
      AuthenticatedOrchestratorOrchestratorIdPlaygroundRoute,
  }

const AuthenticatedOrchestratorOrchestratorIdRouteRouteWithChildren =
  AuthenticatedOrchestratorOrchestratorIdRouteRoute._addFileChildren(
    AuthenticatedOrchestratorOrchestratorIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardLayoutRouteRoute: typeof AuthenticatedDashboardLayoutRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrchestratorOrchestratorIdRouteRoute: typeof AuthenticatedOrchestratorOrchestratorIdRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardLayoutRouteRoute:
    AuthenticatedDashboardLayoutRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrchestratorOrchestratorIdRouteRoute:
    AuthenticatedOrchestratorOrchestratorIdRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedDashboardLayoutRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/orchestrator/$orchestratorId': typeof AuthenticatedOrchestratorOrchestratorIdRouteRouteWithChildren
  '/inbox': typeof AuthenticatedDashboardLayoutInboxRoute
  '/knowledge': typeof AuthenticatedDashboardLayoutKnowledgeRoute
  '/notifications': typeof AuthenticatedDashboardLayoutNotificationsRoute
  '/workspace-settings': typeof AuthenticatedDashboardLayoutWorkspaceSettingsRoute
  '/orchestrator/$orchestratorId/configuration': typeof AuthenticatedOrchestratorOrchestratorIdConfigurationRoute
  '/orchestrator/$orchestratorId/deployment': typeof AuthenticatedOrchestratorOrchestratorIdDeploymentRoute
  '/orchestrator/$orchestratorId/playground': typeof AuthenticatedOrchestratorOrchestratorIdPlaygroundRoute
}

export interface FileRoutesByTo {
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '': typeof AuthenticatedDashboardLayoutRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/orchestrator/$orchestratorId': typeof AuthenticatedOrchestratorOrchestratorIdRouteRouteWithChildren
  '/inbox': typeof AuthenticatedDashboardLayoutInboxRoute
  '/knowledge': typeof AuthenticatedDashboardLayoutKnowledgeRoute
  '/notifications': typeof AuthenticatedDashboardLayoutNotificationsRoute
  '/workspace-settings': typeof AuthenticatedDashboardLayoutWorkspaceSettingsRoute
  '/orchestrator/$orchestratorId/configuration': typeof AuthenticatedOrchestratorOrchestratorIdConfigurationRoute
  '/orchestrator/$orchestratorId/deployment': typeof AuthenticatedOrchestratorOrchestratorIdDeploymentRoute
  '/orchestrator/$orchestratorId/playground': typeof AuthenticatedOrchestratorOrchestratorIdPlaygroundRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/_dashboardLayout': typeof AuthenticatedDashboardLayoutRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/orchestrator/$orchestratorId': typeof AuthenticatedOrchestratorOrchestratorIdRouteRouteWithChildren
  '/_authenticated/_dashboardLayout/inbox': typeof AuthenticatedDashboardLayoutInboxRoute
  '/_authenticated/_dashboardLayout/knowledge': typeof AuthenticatedDashboardLayoutKnowledgeRoute
  '/_authenticated/_dashboardLayout/notifications': typeof AuthenticatedDashboardLayoutNotificationsRoute
  '/_authenticated/_dashboardLayout/workspace-settings': typeof AuthenticatedDashboardLayoutWorkspaceSettingsRoute
  '/_authenticated/orchestrator/$orchestratorId/configuration': typeof AuthenticatedOrchestratorOrchestratorIdConfigurationRoute
  '/_authenticated/orchestrator/$orchestratorId/deployment': typeof AuthenticatedOrchestratorOrchestratorIdDeploymentRoute
  '/_authenticated/orchestrator/$orchestratorId/playground': typeof AuthenticatedOrchestratorOrchestratorIdPlaygroundRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/chat'
    | '/login'
    | '/welcome'
    | '/auth/callback'
    | '/'
    | '/orchestrator/$orchestratorId'
    | '/inbox'
    | '/knowledge'
    | '/notifications'
    | '/workspace-settings'
    | '/orchestrator/$orchestratorId/configuration'
    | '/orchestrator/$orchestratorId/deployment'
    | '/orchestrator/$orchestratorId/playground'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/login'
    | '/welcome'
    | ''
    | '/auth/callback'
    | '/'
    | '/orchestrator/$orchestratorId'
    | '/inbox'
    | '/knowledge'
    | '/notifications'
    | '/workspace-settings'
    | '/orchestrator/$orchestratorId/configuration'
    | '/orchestrator/$orchestratorId/deployment'
    | '/orchestrator/$orchestratorId/playground'
  id:
    | '__root__'
    | '/_authenticated'
    | '/chat'
    | '/login'
    | '/welcome'
    | '/_authenticated/_dashboardLayout'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/orchestrator/$orchestratorId'
    | '/_authenticated/_dashboardLayout/inbox'
    | '/_authenticated/_dashboardLayout/knowledge'
    | '/_authenticated/_dashboardLayout/notifications'
    | '/_authenticated/_dashboardLayout/workspace-settings'
    | '/_authenticated/orchestrator/$orchestratorId/configuration'
    | '/_authenticated/orchestrator/$orchestratorId/deployment'
    | '/_authenticated/orchestrator/$orchestratorId/playground'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/chat",
        "/login",
        "/welcome",
        "/auth/callback"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/_dashboardLayout",
        "/_authenticated/",
        "/_authenticated/orchestrator/$orchestratorId"
      ]
    },
    "/chat": {
      "filePath": "chat.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/welcome": {
      "filePath": "welcome.tsx"
    },
    "/_authenticated/_dashboardLayout": {
      "filePath": "_authenticated/_dashboardLayout/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_dashboardLayout/inbox",
        "/_authenticated/_dashboardLayout/knowledge",
        "/_authenticated/_dashboardLayout/notifications",
        "/_authenticated/_dashboardLayout/workspace-settings"
      ]
    },
    "/auth/callback": {
      "filePath": "auth.callback.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/orchestrator/$orchestratorId": {
      "filePath": "_authenticated/orchestrator/$orchestratorId/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/orchestrator/$orchestratorId/configuration",
        "/_authenticated/orchestrator/$orchestratorId/deployment",
        "/_authenticated/orchestrator/$orchestratorId/playground"
      ]
    },
    "/_authenticated/_dashboardLayout/inbox": {
      "filePath": "_authenticated/_dashboardLayout/inbox.tsx",
      "parent": "/_authenticated/_dashboardLayout"
    },
    "/_authenticated/_dashboardLayout/knowledge": {
      "filePath": "_authenticated/_dashboardLayout/knowledge.tsx",
      "parent": "/_authenticated/_dashboardLayout"
    },
    "/_authenticated/_dashboardLayout/notifications": {
      "filePath": "_authenticated/_dashboardLayout/notifications.tsx",
      "parent": "/_authenticated/_dashboardLayout"
    },
    "/_authenticated/_dashboardLayout/workspace-settings": {
      "filePath": "_authenticated/_dashboardLayout/workspace-settings.tsx",
      "parent": "/_authenticated/_dashboardLayout"
    },
    "/_authenticated/orchestrator/$orchestratorId/configuration": {
      "filePath": "_authenticated/orchestrator/$orchestratorId/configuration.tsx",
      "parent": "/_authenticated/orchestrator/$orchestratorId"
    },
    "/_authenticated/orchestrator/$orchestratorId/deployment": {
      "filePath": "_authenticated/orchestrator/$orchestratorId/deployment.tsx",
      "parent": "/_authenticated/orchestrator/$orchestratorId"
    },
    "/_authenticated/orchestrator/$orchestratorId/playground": {
      "filePath": "_authenticated/orchestrator/$orchestratorId/playground.tsx",
      "parent": "/_authenticated/orchestrator/$orchestratorId"
    }
  }
}
ROUTE_MANIFEST_END */
